# Using buster, a Debian-based Node image, since Python needs to be available to install the project dependencies.
FROM node:lts-buster

WORKDIR /usr/snip-man-dev/
# Hop into a bash shell upon container startup
CMD ["bash"]
