version: '3.9'

networks:
  # single network for all services, only for development
  dev:

services:
  nx-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./services/mongo/.env.dev
      - ./services/postgres/.env.dev
    container_name: snip-man-nx-dev
    restart: always
    entrypoint: >
      bash -c "npm install &&
               npm run generate:prisma &&
               npm run migrate:prisma &&
               bash"
    # Mount the repository root into the container for live file changes
    volumes:
      - ./:/usr/snip-man-dev/
    ports:
      - '5555:5555' # prisma studio mongo
      - '5556:5556' # prisma studio postgres
      - '4200:4200' # web
      - '3333:3333' # server
    networks:
      dev:

  postgres:
    build: ./services/postgres
    env_file: ./services/postgres/.env.dev
    container_name: snip-man-postgres-dev
    restart: always
    ports:
      - '15432:5432' # only to inspect the DB from the host with a db-admin tool, such as DataGrip
    networks:
      dev:

  mongo:
    build: ./services/mongo
    env_file: ./services/mongo/.env.dev
    container_name: snip-man-mongo-dev
    restart: always
    ports:
      - '37017:27017' # only to inspect the DB from the host with a db-admin tool, such as DataGrip
    networks:
      dev:
