# Using buster, a Debian-based Node image, since Python needs to be available to install the project dependencies.
FROM node:lts-buster

# Make sure that we are running the latest version of npm
RUN npm install -g npm@latest

WORKDIR /usr/snip-man-dev/
# Hop into a bash shell upon container startup
CMD ["bash"]
