version: '3.9'

networks:
  web-reverse-proxy:
  server-reverse-proxy:
  postgres-server:
  mongo-server:

services:
  reverse-proxy:
    build: ./services/reverse-proxy
    container_name: snip-man-reverse-proxy
    restart: always
    # Ports as defined in the entries of ./services/reverse-proxy/nginx.conf
    ports:
      - '80:80'
      - '443:443'
      - '3333:3333'
      - '8443:8443'
    networks:
      web-reverse-proxy:
      server-reverse-proxy:

  postgres:
    build: ./services/postgres
    container_name: snip-man-postgres
    restart: always
    environment:
      POSTGRES_USER: snipper
      POSTGRES_PASSWORD: i3nj0yan9ularl0l
      POSTGRES_DB: snip-man
    networks:
      postgres-server:

  mongo:
    build: ./services/mongo
    container_name: snip-man-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: snipper
      MONGO_INITDB_ROOT_PASSWORD: i3nj0yan9ularl0l
      MONGO_INITDB_DATABASE: snip-man
    networks:
      mongo-server:

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    container_name: snip-man-server
    restart: always
    networks:
      web-reverse-proxy:
      server-reverse-proxy:
      postgres-server:
      mongo-server:

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: snip-man-web
    restart: always
    networks:
      web-reverse-proxy:
