version: '3.9'

networks:
  web-reverse-proxy:
  server-reverse-proxy:
  postgres-server:
  mongo-server:

services:
  reverse-proxy:
    build: ./services/reverse-proxy
    container_name: snip-man-reverse-proxy
    restart: always
    # Ports as defined in the entries of ./services/reverse-proxy/nginx.conf
    ports:
      - '80:80'
      - '443:443'
      - '3333:3333'
      - '8443:8443'
    networks:
      web-reverse-proxy:
      server-reverse-proxy:

  postgres:
    build: ./services/postgres
    env_file: ./services/postgres/.env
    container_name: snip-man-postgres
    restart: always
    networks:
      postgres-server:

  mongo:
    build: ./services/mongo
    env_file: ./services/mongo/.env
    container_name: snip-man-mongo
    restart: always
    networks:
      mongo-server:

  prisma-migrate:
    image: snip-man:nx-base
    env_file:
      - ./services/mongo/.env
      - ./services/postgres/.env
    container_name: snip-man-prisma-migrate
    restart: on-failure
    command: ['npm', 'run', 'migrate:prisma']
    depends_on:
      - postgres
      - mongo
    networks:
      postgres-server:
      mongo-server:

  server:
    build:
      context: ./
      dockerfile: ./apps/server/Dockerfile
      target: runner
      args:
        NODE_ENV: production
        PORT: 3333
        NX_BUILD_ARGS: '--prod'
    env_file: ./apps/server/src/assets/.env.production
    container_name: snip-man-server
    restart: always
    depends_on:
      - prisma-migrate
    networks:
      web-reverse-proxy:
      server-reverse-proxy:
      postgres-server:
      mongo-server:

  web:
    build:
      context: ./
      dockerfile: ./apps/web/Dockerfile
      target: runner
      args:
        NODE_ENV: production
        PORT: 4200
        NX_BUILD_ARGS: '--prod'
    container_name: snip-man-web
    restart: always
    depends_on:
      - server
    networks:
      web-reverse-proxy:
