export const progLanguages = [
  { name: 'C++', version: '17' },
  { name: 'C++', version: '20' },
  { name: 'Dart', version: '2.1' },
  { name: 'Elixir', version: '1.1' },
  { name: 'Elm', version: '0.19' },
  { name: 'Erlang', version: '1' },
  { name: 'Go', version: '17' },
  { name: 'Go', version: '18' },
  { name: 'Haskell', version: '13' },
  { name: 'Java', version: '8' },
  { name: 'Java', version: '17' },
  { name: 'JavaScript', version: 'ES5' },
  { name: 'JavaScript', version: 'ES6' },
  { name: 'Kotlin', version: '1.6' },
  { name: 'Lua', version: '3.1' },
  { name: 'PHP', version: '7.0' },
  { name: 'PHP', version: '8.0' },
  { name: 'Python', version: '2' },
  { name: 'Python', version: '3' },
  { name: 'Ruby', version: '2.7' },
  { name: 'Ruby', version: '3.1' },
  { name: 'Rust', version: '1.57' },
  { name: 'Scala', version: '2.1' },
  { name: 'Swift', version: '2.0' },
  { name: 'TypeScript', version: '4.6' },
];
