export const progLanguages = [
  { name: 'C#', version: '1.0' },
  { name: 'C', version: '1.0' },
  { name: 'C++', version: '1.0' },
  { name: 'Clojure', version: '1.0' },
  { name: 'CoffeeScript', version: '1.0' },
  { name: 'Elixir', version: '1.0' },
  { name: 'Elm', version: '1.0' },
  { name: 'Erlang', version: '1.0' },
  { name: 'F#', version: '1.0' },
  { name: 'Go', version: '1.0' },
  { name: 'Haskell', version: '1.0' },
  { name: 'Java', version: '1.0' },
  { name: 'JavaScript', version: '1.0' },
  { name: 'Kotlin', version: '1.0' },
  { name: 'Lua', version: '1.0' },
  { name: 'Perl', version: '1.0' },
  { name: 'PHP', version: '1.0' },
  { name: 'Python', version: '1.0' },
  { name: 'Ruby', version: '1.0' },
  { name: 'Rust', version: '1.0' },
  { name: 'Scala', version: '1.0' },
  { name: 'Swift', version: '1.0' },
  { name: 'TypeScript', version: '1.0' },
];
